Initial functionality and tests.
digitalbazaar/pdf417-dl-canonicalizer pull request #1
Opened 2024-02-14 23:24 UTC by wes-smith

2024-02-15 15:59 UTC, dlongley requested changes
Not a full review, just what I had time for just now. Thanks, good progress!

2024-02-15 15:59 UTC, dlongley commented on lib/canonize.js
> +
```suggestion
```

2024-02-15 15:59 UTC, dlongley commented on lib/canonize.js
> +export function canonizedBytesFromPdfBytes({pdfBytes} = {}) {
If wonder if we can use shorter names here without any issue?

```suggestion
export function canonicalize({pdfBytes} = {}) {
```

2024-02-15 15:59 UTC, dlongley commented on lib/canonize.js
> +export async function hashFromPdfBytes({pdfBytes} = {}) {
Shorter name?

```suggestion
export async function hashCanonicalized({pdfBytes} = {}) {
```

2024-02-15 15:59 UTC, dlongley commented on lib/canonize.js
> +    'DAK', 'DCS', 'DAC', 'DAD', 'DCB', 'DAI', 'DAQ', 'DAG', 'DCG'];
```suggestion
  const included_fields = [
    'DBA', 'DBD', 'DBB', 'DBC', 'DAY', 'DAU', 'DAJ',
    'DAK', 'DCS', 'DAC', 'DAD', 'DCB', 'DAI', 'DAQ', 'DAG', 'DCG'
  ];
```

2024-02-15 15:59 UTC, dlongley commented on lib/canonize.js
> +    subfile_indicator_index + 1) + 2);
We perhaps haven't gotten the linter to do this yet (or we don't have the right linter config in this particular module), but our style is: if you drop any function param or array element, you drop them all:

```suggestion
  const subfiles = pdfDataAsString.slice(
    pdfDataAsString.indexOf('DL', subfile_indicator_index + 1) + 2);
```

2024-02-15 15:59 UTC, dlongley commented on lib/canonize.js
> +  const subfile_indicator_index = pdfDataAsString.indexOf('DL');
Don't mix snake_case and camelCase ... just use camelCase in all DB libs. We only use other cases if some other module has already established a precedent/need for it (we prefer camelCase but not over prefer internal consistency).

2024-02-15 15:59 UTC, dlongley commented on lib/canonize.js
> +      if(elem.indexOf(field) === 0) {
Is this the right comparison? Is it just if the element starts with a field ... do we need any delimiter check? Are the field names always 3 chars long? Just asking, that seems right, but I don't know off hand so figured I'd double check.

2024-02-15 15:59 UTC, dlongley commented on lib/canonize.js
> +  const canonicalizedData = data_to_canonicalize.sort().join('');
We might need a note here that this sort is actually on UTF-16 code units, which is subtly different from Unicode code point order. This almost never matters, but I don't know if it actually might for this sort of data. We should turn this into an issue and get it sorted out, no pun intended.

2024-02-15 15:59 UTC, dlongley commented on lib/platform.js
> +export const crypto = webcrypto;
I actually think node 18+ has caught up to the browser so you can just use `globalThis.crypto` now ... so there might be no need for the platform splitting here.

2024-02-15 17:21 UTC, wes-smith commented on lib/canonize.js
> +      if(elem.indexOf(field) === 0) {
field names are 3 chars, and delimiters are split on so shouldn't exist in dlElements

2024-02-15 17:23 UTC, wes-smith commented on lib/platform.js
> +export const crypto = webcrypto;
going to leave this for now... for some reason webcrypto was working locally but failing the GitHub actions check... Lehn fixed it for me and I'm a little scared to touch it. Let me know on rereview if this change is important and I will loop him in.

2024-02-15 23:09 UTC, davidlehn commented on lib/platform.js
> +export const crypto = webcrypto;
It's never easy.
- Node 18: no globalThis.crypto.  in console globalThis.crypto === node:crypto module.  crypto.subtle === crypto.webcrypto.subtle.
- Node 20: globalThis.crypto === node:crypto.webcrypto.  in console same.  crypto.subtle doesn't exist.  need to access webcrypto.subtle (which is globalThis.crypto.subtle).
- Browser: globalThis.crypto === webcrypto.  crypto.subtle is what you expect.
- Solution here not meant to be scary. :-)  It seems the most straightforward way to expose webcrypto across those three platforms.  And react native needs a polyfill of course.

2024-02-15 23:24 UTC, davidlehn commented on README.md
> +hashFromPdfBytes({pdfBytes})
Fix all these to reflect renames.

2024-02-15 23:24 UTC, davidlehn commented on test/10-main.spec.js
> +} from '../lib/canonize.js';
If testing the main module API, use the normal entry point.  `index.js` wasn't updated after rename, so the tests pass, but the module is broken.  If testing some part of the lib on it's own, or private local APIs, then use whatever is needed.
```suggestion
} from '../lib/index.js';
```

2024-02-15 23:24 UTC, davidlehn commented on test/testCanonize.js
> +  hashCanonicalized} from '../lib/canonize.js';
I can't speak for others, but I prefer the following style.  Either way, I think `index.js` can be used?
```suggestion
import {
  base64UrlFromPdfBytes,
  canonicalize,
  hashCanonicalized
} from '../lib/index.js';
```

2024-02-15 23:24 UTC, davidlehn commented on lib/index.js
> +  hashFromPdfBytes
- Fix rename.
- A better solution might be to drop `canonize.js` and move the contents into `index.js`.  The extra file and export bouncing isn't needed in this simple module and led to bugs in the other comments.

2024-02-15 23:30 UTC, davidlehn commented on lib/platform.js
> +export const crypto = webcrypto;
And this pattern makes it fairly easy to add an specific async call like `sha256()` to each file, and the node one can use the faster native crypto API.  But if performance isn't a measured issue, easier to simplify and use only webcrypto API to start.

2025-04-03 20:43 UTC, dlongley commented
Closing in favor of PR #4.

2025-04-03 20:43 UTC, closed without merging